[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "jellyname"
version = "0.0.0"
dependencies = [
    "tmdbsimple==2.9.1",
    "prompt_toolkit==3.0.48",
    "pymkv2==2.1.0",
]
